[package]
name = "sakura-entity"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "entity"
#path = "src/lib.rs"

[dependencies]
chrono = {workspace = true}
#sea-orm = {workspace = true}
serde = {workspace = true}

sqlx={workspace = true}