env = "dev"

[server]
host = "0.0.0.0"
port = 8080

# ***** Database相关配置 Start *****
# Phoenix
[databases.sources.phoenix]
db_type = "mysql"
url = "mysql://srvjava_uat:Test2018RDBSrvjava1210@rm-m5eu9o0h47352viavio.mysql.rds.aliyuncs.com:3306/phoenix?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8"
host = "rm-m5eu9o0h47352viavio.mysql.rds.aliyuncs.com"
port = 3306
username = "srvjava_uat"
password = "Test2018RDBSrvjava1210"
database = "phoenix"
min_connections = 2
max_connections = 30
idle_timeout = 60

# sakura_huajian_activity
[databases.sources.activity]
db_type = "mysql"
host = "rm-m5eu9o0h47352viavio.mysql.rds.aliyuncs.com"
port = 3306
username = "srvjava_uat"
password = "Test2018RDBSrvjava1210"
database = "sakura_huajian_activity"
min_connections = 2
max_connections = 30
idle_timeout = 60

# ***** Database End *****


# ***** Redis Start *****
[redis]
uri="redis://:HuaJian2019testRedis@srv-redis-uat-io.kaiqi.xin:7001/0"
max_size=10

# ***** Redis End *****

# ***** MQ Start *****
[rabbit]
uri="amqp://admin:YR888888@srv-rbtmq-uat-io.kaiqi.xin:5672/%2f"
pool_max_size=10

# ***** MQ Start *****




# ***** Log相关配置 Start *****

[log]
level = "debug"
show_module_path = true
show_line_numbers = true
format = "text"
show_target = true
show_thread_id = false
async_logging = true

[log.console]
enabled = true
use_colors = true

[log.file]
enabled = true
path = "logs/app.log"
rotation = "daily"
max_size = 100
max_files = 7

[log.module_filters]
"sqlx::query" = "info"
"tower_http::trace" = "debug"
"hyper::proto" = "warn"

# ** Log相关配置 End **

