env = "prod"

[server]
host = "0.0.0.0"
port = 8080

[log]
[log.logging]
log_level = "INFO"
log_path = "./tmp/logs"
file_rotation = "daily"
log_format = "json"  # 可选：json 或 plain

[log.audit]
enabled = true
audit_log_level = "DEBUG"


# ** Redis **
[redis]
uri="redis://:HuaJian2019testRedis@srv-redis-uat-io.kaiqi.xin:7001/0"
max_size=10


# ** MQ **
[rabbit]
uri="amqp://admin:YR888888@srv-rbtmq-uat-io.kaiqi.xin:5672/%2f"
pool_max_size=10


# ** MYSQL 数据库 **
[mysql]
[mysql.sm_phoenix]
url = "mysql://srvjava_uat:Test2018RDBSrvjava1210@rm-m5eu9o0h47352viavio.mysql.rds.aliyuncs.com:3306/sm_phoenix?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8"
max_connections = 10
idle_timeout = 60

[mysql.sakura_pay]
url = "mysql://srvjava_uat:Test2018RDBSrvjava1210@rm-m5eu9o0h47352viavio.mysql.rds.aliyuncs.com:3306/sakura_pay?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8"
max_connections = 10
idle_timeout = 60
