[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = {workspace = true}

serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
