[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]

serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}

chrono = {workspace = true}

sqlx = {workspace = true}
