[package]
name = "web-core"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = {workspace = true}

tokio = {workspace = true}

serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
serde_urlencoded = {workspace = true}

base64 = {workspace = true}
hmac = {workspace = true}
sha1 = {workspace = true}
uuid = {workspace = true}

chrono = {workspace = true}
url = {workspace = true}
reqwest = {workspace = true, features = ["json"]}

thiserror = {workspace = true}


lazy_static = {workspace = true}
inventory = {workspace = true}

futures-util = {workspace = true}
tracing = {workspace = true}

sakura-macros = {path = "../macros"}
