[package]
name = "web-core"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = {workspace = true}

actix-web-httpauth = "0.8.2"
jsonwebtoken = "9.3.1"

tokio = {workspace = true}

serde = {workspace = true, features = ["derive"]}

dotenvy = {workspace = true}

lazy_static = {workspace = true}
inventory = {workspace = true}

futures-util = {workspace = true}
tracing = {workspace = true}

sakura-macros = {path = "../macros"}
