version: '3.8'

services:
  ssl-automator:
    image: will/ssl-automator:latest
    container_name: ssl-automator
    restart: unless-stopped
    volumes:
      - ssl_config:/config
      - ssl_certs:/certs
      - ./webroots:/webroots
    environment:
      - RUST_LOG=info
      - TZ=Asia/Shanghai
    # 可选：与Nginx或其他Web服务器连接的网络配置
    networks:
      - web

  # 示例Web服务器配置(可选)
#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    restart: unless-stopped
#    depends_on:
#      - ssl-automator
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./webroots:/var/www
#      - ssl_certs:/etc/ssl/certs:ro
#    networks:
#      - web

volumes:
  ssl_config:
    name: ssl_automator_config
  ssl_certs:
    name: ssl_automator_certs

networks:
  web:
    name: web_network
